name: Destroy RDS Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "destroy" to confirm deletion'
        required: true
        default: ''

jobs:
  destroy:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_destroy == 'destroy'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.FIAP_POS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.FIAP_POS_AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.FIAP_POS_AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.FIAP_POS_AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Destroy
        working-directory: infra
        run: terraform destroy -auto-approve
        env:
          AWS_ROLE_ARN: ${{ secrets.FIAP_POS_AWS_ROLE_ARN }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

      - name: Done
        run: echo "RDS Infrastructure destroyed successfully"
